version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.8  # Use a Python image, or another image that suits your needs

jobs:
  setup:
    executor: default
    steps:
      - checkout  # Check out the code from your repository

      # Install required packages
      - run:
          name: Install required packages
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip wget

      # Download and extract Groovy
      - run:
          name: Download Groovy
          command: |
            wget https://archive.apache.org/dist/groovy/2.4.10/apache-groovy-sdk-2.4.10.zip -O groovy.zip

      - run:
          name: Extract Groovy
          command: |
            sudo unzip groovy.zip -d /opt

      # Verify the installation
      - run:
          name: Verify Groovy Installation
          command: |
            sudo /opt/apache-groovy-sdk-2.4.10/bin/groovy -version

      # Clean up
      - run:
          name: Clean up
          command: |
            rm -f groovy.zip

workflows:
  version: 2
  build:
    jobs:
      - setup
