version: 2.1

executors:
  default:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  setup:
    executor: default
    steps:
      - checkout

      - run:
          name: Install Basic Utilities
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip wget curl bash software-properties-common gnupg

      - run:
          name: Verify Java and Groovy Installation
          command: |
            export JAVA_HOME=/usr/local/openjdk-11
            export PATH=$JAVA_HOME/bin:$PATH
            echo "JAVA_HOME is set to: $JAVA_HOME"
            echo "PATH is set to: $PATH"
            java -version
            groovy --version

      - run:
          name: Run Build Script
          command: |
            groovy Jenkins/shared-libraries/src/org/common/build/BuildWithNpm.groovy

workflows:
  version: 2
  build:
    jobs:
      - setup
