version: 2.1

executors:
  custom-docker:
    docker:
      - image: bharathoptdocker/mycircleci:latest # Use your custom Docker image

jobs:
  build:
    executor: custom-docker
    steps:
      - checkout

      - run:
          name: Build App
          command: |
            cd ~/project
            npm install
            npm run build

      - run:
          name: Run Tests
          command: |
            cd ~/project
            npm test

      - run:
          name: Verify SonarQube Scanner Installation
          command: |
            sonar-scanner --version

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker Image
          command: |
            cd ~/project
            docker build -t ${DOCKER_REPO}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} .

      - run:
          name: Scan Docker Image
          command: |
            trivy image ${DOCKER_REPO}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}

      - run:
          name: Publish Docker Image
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push ${DOCKER_REPO}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}

workflows:
  version: 2
  build:
    jobs:
      - build
