version: 2.1

executors:
  default:
    docker:
      - image: quay.io/ukhomeofficedigital/aws-alpine-jdk17:v17.0.10  # Base Docker image

jobs:
  git_checkout:
    executor: default
    steps:
      - checkout

      - run:
          name: Install Necessary Packages
          command: |
            apk add --no-cache wget curl git python3 py3-pip unzip ansible-lint gcompat

      - run:
          name: Install SonarScanner
          command: |
            export SONAR_SCANNER_VER=4.8.1.3023
            wget -O /tmp/sonar-scanner-cli-${SONAR_SCANNER_VER}.zip \
              https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VER}.zip
            unzip /tmp/sonar-scanner-cli-${SONAR_SCANNER_VER}.zip -d /opt/
            rm -rf /tmp/sonar-scanner-cli-${SONAR_SCANNER_VER}.zip
            export SONAR_SCANNER_OPTS="-Xmx512m -Dsonar.host.url=https://sonarqube.digital.homeoffice.gov.uk/"
            export PATH=/opt/sonar-scanner-${SONAR_SCANNER_VER}/bin:${PATH}

      - run:
          name: Verify SonarScanner Installation
          command: |
            sonar-scanner --version || {
              echo "SonarScanner not found. Please check the installation."
              exit 1
            }

      - run:
          name: Install Groovy
          command: |
            wget -qO /tmp/groovy.zip https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/apache-groovy-binary-5.0.0-alpha-9.zip
            unzip /tmp/groovy.zip -d /opt
            ln -sf /opt/groovy-5.0.0-alpha-9/bin/groovy /usr/local/bin/groovy
            chmod +x /opt/groovy-5.0.0-alpha-9/bin/groovy

      - run:
          name: Set GROOVY_HOME and PATH
          command: |
            echo 'export GROOVY_HOME=/opt/groovy-5.0.0-alpha-9' >> $BASH_ENV
            echo 'export PATH=$GROOVY_HOME/bin:$PATH' >> $BASH_ENV

      - run:
          name: Verify Groovy Installation
          command: |
            groovy --version || /opt/groovy-5.0.0-alpha-9/bin/groovy --version

      - run:
          name: Install Node.js and npm
          command: |
            curl -fsSL https://deb.nodesource.com/setup_16.x | apk add --no-cache nodejs npm
            node --version
            npm --version

      - run:
          name: Run Build Script
          command: |
            groovy Jenkins/shared-libraries/src/org/common/build/BuildWithNpm.groovy

      - run:
          name: Run Test Script
          command: |
            groovy Jenkins/shared-libraries/src/org/common/unitTest/UnitTestWithNpm.groovy

      - run:
          name: Run SonarScanner
          command: |
            sonar-scanner \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.organization=${SONAR_ORGANIZATION} \
              -Dsonar.sources=${SONAR_SOURCES_DIR} \
              -Dsonar.java.binaries=${SONAR_BINARIES_DIR} \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${SONAR_TOKEN} \
              > sonar-scanner.log 2>&1 || {
                echo "SonarScanner failed with exit code $?. See sonar-scanner.log for details."
                cat sonar-scanner.log
                exit 1
              }

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build Docker Image
          command: |
            groovy Jenkins/shared-libraries/vars/common/dockerUtil/DockerUtil.groovy

      - run:
          name: Scan Docker Image
          command: |
            groovy Jenkins/shared-libraries/vars/common/dockerUtil/DockerScan.groovy

      - run:
          name: Publish Docker Image
          command: |
            groovy Jenkins/shared-libraries/vars/common/containerPublish/DockerHubPublish.groovy

workflows:
  version: 2
  build:
    jobs:
      - git_checkout
