version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Choose the appropriate Docker image for your environment
    steps:
      - checkout  # Check out the source code

      # Print environment variables
      - run:
          name: Print Environment Variables
          command: |
            printenv

      # Print the directory structure at the default location
      - run:
          name: List Directory Structure at Default Directory
          command: |
            echo "Directory structure at /home/circleci/project:"
            ls -R /home/circleci/project || echo "Directory not found"

      # Set BASE_DIR environment variable
      - run:
          name: Set BASE_DIR
          command: |
            echo "export BASE_DIR=/home/circleci/project/build_js_react_app/Jenkins/shared-libraries" >> $BASH_ENV
            source $BASH_ENV
            echo "BASE_DIR is set to: ${BASE_DIR}"

      # List the directory structure at BASE_DIR
      - run:
          name: List Directory Structure at BASE_DIR
          command: |
            echo "Directory structure at BASE_DIR:"
            ls -R ${BASE_DIR} || echo "Directory not found"

      # Install required packages
      - run:
          name: Install Java and other packages
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip wget openjdk-11-jdk

      # Install Groovy
      - run:
          name: Install Groovy
          command: |
            wget https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/apache-groovy-binary-5.0.0-alpha-9.zip -O groovy.zip
            sudo unzip groovy.zip -d /opt
            sudo ln -sf /opt/groovy-5.0.0-alpha-9/bin/groovy /usr/local/bin/groovy
            sudo chmod +x /opt/groovy-5.0.0-alpha-9/bin/groovy
 # Set GROOVY_HOME and update PATH environment variable
      - run:
          name: Set GROOVY_HOME and PATH
          command: |
            echo 'export GROOVY_HOME=/opt/groovy-5.0.0-alpha-9' >> $BASH_ENV
            echo 'export PATH=$GROOVY_HOME/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

      # Verify Groovy installation
      - run:
          name: Verify Groovy Installation
          command: |
            groovy --version || /opt/groovy-5.0.0-alpha-9/bin/groovy --version

      # Install Node.js and npm
      - run:
          name: Install Node.js and npm
          command: |
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node --version
            npm --version

      # Run Groovy script for build
      - run:
          name: Run Build Script
          command: |
            groovy Jenkins/shared-libraries/src/org/common/build/BuildWithNpm.groovy | tee build-script.log

      # Run Groovy script for test
      - run:
          name: Run Test Script
          command: |
            groovy Jenkins/shared-libraries/src/org/common/unitTest/UnitTestWithNpm.groovy | tee test-script.log


workflows:
  version: 2
  build:
    jobs:
      - build
