version: 2.1

executors:
  default:
    docker:
      - image: your-dockerhub-username/your-custom-image:latest  # Your custom Docker image

jobs:
  setup:
    executor: default
    steps:
      - checkout

      # Build and test application
      - run:
          name: Build App
          command: |
            cd ~/project
            npm install
            npm run build

      - run:
          name: Run Unit Tests
          command: |
            cd ~/project
            npm test

  sonar_scan:
    executor: default
    steps:
      - checkout

      # Run SonarQube scan
      - run:
          name: Run SonarQube Scan
          command: |
            cd ~/project
            sonar-scanner

  docker_build:
    executor: default
    steps:
      - checkout

      # Build Docker image
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: |
            cd ~/project
            if [ -z "$DOCKER_REPO" ] || [ -z "$DOCKER_IMAGE_NAME" ] || [ -z "$DOCKER_IMAGE_TAG" ]; then
              echo "Docker environment variables are not set."
              exit 1
            fi
            docker build -t ${DOCKER_REPO}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} .

  docker_scan:
    executor: default
    steps:
      - checkout

      # Scan Docker image with Trivy
      - run:
          name: Scan Docker Image
          command: |
            trivy image ${DOCKER_REPO}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}

  docker_publish:
    executor: default
    steps:
      - checkout

      # Publish Docker image
      - run:
          name: Publish Docker Image
          command: |
            if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ]; then
              echo "Docker credentials are not set."
              exit 1
            fi
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push ${DOCKER_REPO}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup
      - sonar_scan:
          requires:
            - setup
      - docker_build:
          requires:
            - sonar_scan
      - docker_scan:
          requires:
            - docker_build
      - docker_publish:
          requires:
            - docker_scan
