version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:16  # Adjust Node.js version as needed

jobs:
  setup:
    executor: docker-executor
    parameters:
      GIT_SOURCE_CODE_URL:
        type: string
        default: "https://github.com/bharathkoptit/build_js_react_app.git"
      SOURCE_CODE_BRANCH_NAME:
        type: string
        default: "master"
    steps:
      - checkout
      - run:
          name: Print Parameters
          command: |
            echo "GIT_SOURCE_CODE_URL: << parameters.GIT_SOURCE_CODE_URL >>"
            echo "SOURCE_CODE_BRANCH_NAME: << parameters.SOURCE_CODE_BRANCH_NAME >>"
      - run:
          name: Prepare Directory
          command: |
            if [ -d ~/project ]; then
              rm -rf ~/project
            fi
            mkdir -p ~/project
      - run:
          name: Checkout Repository
          command: |
            git clone << parameters.GIT_SOURCE_CODE_URL >> ~/project
            cd ~/project
            if git show-ref --verify --quiet refs/heads/<< parameters.SOURCE_CODE_BRANCH_NAME >>; then
              git checkout << parameters.SOURCE_CODE_BRANCH_NAME >>
            else
              echo "Branch '<< parameters.SOURCE_CODE_BRANCH_NAME >>' not found. Available branches:"
              git branch -r
              exit 1
            fi
      - run:
          name: Install Node.js Dependencies
          command: |
            cd ~/project
            npm install
      - run:
          name: Install Groovy
          command: |
            sudo apt-get update
      
