version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:12

jobs:
  setup:
    executor: node-executor

    parameters:
      GIT_SOURCE_CODE_URL:
        type: string
        default: "default_git_repo_url"
      SOURCE_CODE_BRANCH_NAME:
        type: string
        default: "default_branch"
      DOCKER_REPO:
        type: string
        default: "default_docker_repo"
      DOCKER_IMAGE_NAME:
        type: string
        default: "default_image_name"
      DOCKER_IMAGE_TAG:
        type: string
        default: "default_image_tag"
      SONAR_PROJECT_KEY:
        type: string
        default: "default_sonar_project_key"
      SONAR_ORGANIZATION:
        type: string
        default: "default_sonar_org"
      SONAR_SOURCES_DIR:
        type: string
        default: "default_sonar_source_dir"

    steps:
      - checkout

      - run:
          name: Print Parameters
          command: |
            echo "GIT_SOURCE_CODE_URL: << parameters.GIT_SOURCE_CODE_URL >>"
            echo "SOURCE_CODE_BRANCH_NAME: <<
