version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.8

jobs:
  setup_environment:
    executor: default
    steps:
      - checkout

      - run:
          name: Install Basic Utilities and Java
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip wget curl openjdk-11-jdk bash

      - run:
          name: Install Groovy
          command: |
            wget -qO /tmp/groovy.zip https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/apache-groovy-binary-5.0.0-alpha-9.zip
            sudo unzip /tmp/groovy.zip -d /opt
            sudo ln -sf /opt/groovy-5.0.0-alpha-9/bin/groovy /usr/local/bin/groovy
            sudo chmod +x /opt/groovy-5.0.0-alpha-9/bin/groovy

      - run:
          name: Set GROOVY_HOME and PATH
          command: |
            echo 'export GROOVY_HOME=/opt/groovy-5.0.0-alpha-9' >> $BASH_ENV
            echo 'export PATH=$GROOVY_HOME/bin:$PATH' >> $BASH_ENV

      - run:
          name: Install Node.js and npm
          command: |
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node --version
            npm --version

      - run:
          name: Install SonarScanner
          command: |
            curl -L -o /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.9.2.2747-linux.zip
            if [ $? -ne 0 ] || [ ! -f /tmp/sonar-scanner.zip ]; then
              echo "Failed to download SonarScanner or the file does not exist"
              exit 1
            fi
            file_type=$(file -b /tmp/sonar-scanner.zip)
            if [[ "$file_type" != "Zip archive data"* ]]; then
              echo "Downloaded file is not a valid ZIP archive: $file_type"
              exit 1
            fi
            sudo unzip /tmp/sonar-scanner.zip -d /opt/sonar-scanner
            if [ $? -ne 0 ]; then
              echo "Failed to unzip SonarScanner"
              exit 1
            fi
            sudo ln -sf /opt/sonar-scanner/sonar-scanner-4.9.2.2747-linux/bin/sonar-scanner /usr/local/bin/sonar-scanner
            sudo chmod +x /usr/local/bin/sonar-scanner

      - run:
          name: Verify Installations
          command: |
            groovy --version
            node --version
            npm --version
            sonar-scanner --version

  build_test_deploy:
    executor: default
    steps:
      - checkout

      - run:
          name: Run Build Script
          command: |
            groovy Jenkins/shared-libraries/src/org/common/build/BuildWithNpm.groovy

      - run:
          name: Run Test Script
          command: |
            groovy Jenkins/shared-libraries/src/org/common/unitTest/UnitTestWithNpm.groovy

      - run:
          name: Run SonarScanner
          command: |
            sonar-scanner \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.organization=${SONAR_ORGANIZATION} \
              -Dsonar.sources=${SONAR_SOURCES_DIR} \
              -Dsonar.java.binaries=${SONAR_BINARIES_DIR} \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${SONAR_TOKEN} \
              > sonar-scanner.log 2>&1 || {
                echo "SonarScanner failed with exit code $?. See sonar-scanner.log for details."
                cat sonar-scanner.log
                exit 1
              }

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build Docker Image
          command: |
            groovy Jenkins/shared-libraries/vars/common/dockerUtil/DockerUtil.groovy

      - run:
          name: Scan Docker Image
          command: |
            groovy Jenkins/shared-libraries/vars/common/dockerUtil/DockerScan.groovy

      - run:
          name: Publish Docker Image
          command: |
            groovy Jenkins/shared-libraries/vars/common/containerPublish/DockerHubPublish.groovy

workflows:
  version: 2
  build:
    jobs:
      - setup_environment
      - build_test_deploy:
          requires:
            - setup_environment
