version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:12

jobs:
  setup:
    executor: node-executor

    parameters:
      GIT_SOURCE_CODE_URL:
        type: string
        default: "https://github.com/bharathkoptit/build_js_react_app.git"
      SOURCE_CODE_BRANCH_NAME:
        type: string
        default: "master"

    steps:
      - checkout:
          path: ~/project

      - run:
          name: Print Parameters
          command: |
            echo "GIT_SOURCE_CODE_URL: << parameters.GIT_SOURCE_CODE_URL >>"
            echo "SOURCE_CODE_BRANCH_NAME: << parameters.SOURCE_CODE_BRANCH_NAME >>"

      - run:
          name: Prepare Directory
          command: |
            if [ -d ~/project ]; then
              rm -rf ~/project
            fi
            mkdir -p ~/project

      - run:
          name: Checkout Repository
          command: |
            git clone << parameters.GIT_SOURCE_CODE_URL >> ~/project
            cd ~/project
            if git show-ref --verify --quiet refs/heads/<< parameters.SOURCE_CODE_BRANCH_NAME >>; then
              git checkout << parameters.SOURCE_CODE_BRANCH_NAME >>
            else
              echo "Branch '<< parameters.SOURCE_CODE_BRANCH_NAME >>' not found. Available branches:"
              git branch -r
              exit 1
            fi

      - run:
          name: Update APT Sources
          command: |
            sudo sed -i 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' /etc/apt/sources.list
            sudo sed -i 's|http://security.debian.org/debian-security|http://archive.debian.org/debian-security|g' /etc/apt/sources.list
            sudo apt-get update

      - run:
          name: Install Dependencies
          command: |
            sudo apt-get install -y groovy

      - run:
          name: Load Groovy Scripts
          command: |
            # Define baseDir for Jenkins shared libraries
            baseDir=~/project/Jenkins/shared-libraries

            # Load scripts using dynamically constructed paths
            load_script() {
              type=$1
              technology=$2
              script_name=$3
              script_path="${baseDir}/${type}/${technology}/${script_name}.groovy"
              echo "Loading script: ${script_path}"
              groovy ${script_path}
            }

            # Load scripts from 'vars' directory
            load_script "vars/common/scm-util" "git" "GitCheckout"
            load_script "vars/common" "codeAnalysis" "PerformSonarAnalysisForReactjs"
            load_script "vars/common" "dockerUtil" "DockerUtil"
            load_script "vars/common" "containerPublish" "DockerHubPublish"
            load_script "vars/common" "dockerUtil" "DockerScan"
            # Load scripts from 'src' directory
            load_script "src/org/common" "build" "BuildWithNpm"
            load_script "src/org/common" "unitTest" "UnitTestWithNpm"

workflows:
  version: 2
  setup_and_load:
    jobs:
      - setup:
          GIT_SOURCE_CODE_URL: "https://github.com/bharathkoptit/build_js_react_app.git"
          SOURCE_CODE_BRANCH_NAME: "master"
