version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14  # Replace with the Node.js version you need
    working_directory: ~/project

jobs:
  install_groovy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Groovy
          command: |
            wget https://downloads.apache.org/groovy/enterprise/groovy-4.0.11/bin/groovy-4.0.11.zip
            unzip groovy-4.0.11.zip
            sudo mv groovy-4.0.11 /usr/local/groovy
            export PATH=$PATH:/usr/local/groovy/bin
            groovy --version

  load_scripts:
    parameters:
      baseDir:
        type: string
        default: "Jenkins/shared-libraries"
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Load Scripts
          command: |
            baseDir="${CIRCLE_WORKING_DIRECTORY}/${BASE_DIR}"
            # Function to load Groovy scripts
            loadScript() {
              type=$1
              technology=$2
              scriptName=$3
              scriptPath="${baseDir}/${type}/${technology}/${scriptName}.groovy"
              groovy "${scriptPath}"
            }

            # Load Groovy scripts
            gitCheckoutScript=$(loadScript "vars/common/scm-util" "git" "GitCheckout")
            sonarScript=$(loadScript "vars/common" "codeAnalysis" "PerformSonarAnalysisForReactjs")
            dockerBuildScript=$(loadScript "vars/common" "dockerUtil" "DockerUtil")
            dockerPublishScript=$(loadScript "vars/common" "containerPublish" "DockerHubPublish")
            dockerScanScript=$(loadScript "vars/common" "dockerUtil" "DockerScan")
            buildWithNpmScript=$(loadScript "src/org/common" "build" "BuildWithNpm")
            unitTestWithNpmScript=$(loadScript "src/org/common" "unitTest" "UnitTestWithNpm")

  git_checkout:
    parameters:
      sourceCodeUrl:
        type: string
      sourceCodeBranchName:
        type: string
      gitSourceCodeCredential:
        type: string
    executor: node-executor
    steps:
      - run:
          name: Git Checkout Source Code Repo
          command: |
            git config --global credential.helper store
            echo "https://${GIT_USER}:${GIT_TOKEN}@${SOURCE_CODE_URL}" > ~/.git-credentials
            git clone -b "${SOURCE_CODE_BRANCH_NAME}" "${SOURCE_CODE_URL}"

  install_dependencies:
    executor: node-executor
    steps:
      - run:
          name: Install Dependencies
          command: npm install

  build:
    executor: node-executor
    steps:
      - run:
          name: Build
          command: npm run build

  test:
    executor: node-executor
    steps:
      - run:
          name: Unit Test
          command: npm test

  sonar_analysis:
    executor: node-executor
    steps:
      - run:
          name: SonarQube Analysis
          command: groovy -e "${sonarScript}.performSonarCloudAnalysis('${SONAR_PROJECT_KEY}', '${SONAR_ORGANIZATION}', '${SONAR_SOURCES_DIR}', '${SONAR_TOKEN}')"

  docker_build:
    docker:
      - image: circleci/node:14
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Docker Build
          command: groovy -e "${dockerBuildScript}.dockerBuild('${DOCKER_IMAGE_NAME}', '${DOCKER_IMAGE_TAG}')"

  docker_scan:
    docker:
      - image: circleci/node:14
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Docker Scan
          command: groovy -e "${dockerScanScript}.dockerScan('${DOCKER_IMAGE_NAME}')"

  docker_publish:
    docker:
      - image: circleci/node:14
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Docker Publish
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            groovy -e "${dockerPublishScript}.publishToContainer('${DOCKER_IMAGE_NAME}', '${DOCKER_REPO}', '${DOCKER_IMAGE_TAG}', '${DOCKER_CREDENTIAL}')"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install_groovy
      - load_scripts:
          baseDir: "Jenkins/shared-libraries"
          requires:
            - install_groovy
      - git_checkout:
          sourceCodeUrl: "https://github.com/example/repo.git"
          sourceCodeBranchName: "main"
          gitSourceCodeCredential: "git-credential-id"
          requires:
            - load_scripts
      - install_dependencies:
          requires:
            - git_checkout
      - build:
          requires:
            - install_dependencies
      - test:
          requires:
            - build
      - sonar_analysis:
          requires:
            - test
      - docker_build:
          requires:
            - sonar_analysis
      - docker_scan:
          requires:
            - docker_build
      - docker_publish:
          requires:
            - docker_scan
