version: 2.1

executors:
  java-node-docker-executor:
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      JAVA_HOME: /usr/local/openjdk-11
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    working_directory: /home/circleci/project

jobs:
  build:
    executor: java-node-docker-executor
    steps:
      - run:
          name: Build with Groovy Script
          command: |
            export JAVA_HOME=/usr/local/openjdk-11
            groovy buildWithNpmScript.groovy

  test:
    executor: java-node-docker-executor
    steps:
      - run:
          name: Unit Test
          command: |
            npm test

  # Additional jobs like `sonar_analysis`, `docker_build`, `docker_scan`, etc.

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      # Additional jobs dependencies
