version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.8  # Use the Python 3.8 image or any other base image you prefer

jobs:
  setup:
    executor: default
    steps:
      - checkout  # Check out the main repository

      - run:
          name: Install Java, Node.js, and Dependencies
          command: |
            # Update package lists and install Java
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk npm docker.io curl

            # Ensure npm is available
            sudo ln -sf /usr/bin/npm /usr/local/bin/npm

  build:
    executor: default
    steps:
      - run:
          name: Install npm Dependencies and Build
          command: |
            npm install
            npm run build

  docker_build_and_push:
    executor: default
    steps:
      - setup_remote_docker:
          version: 20.10.7  # Adjust Docker version if needed
      - run:
          name: Docker Build
          command: |
            docker build -t ${DOCKER_REPO}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} .
      - run:
          name: Docker Push
          command: |
            docker push ${DOCKER_REPO}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
      - run:
          name: Docker Scan
          command: |
            docker scan ${DOCKER_REPO}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}

  sonar_analysis:
    executor: default
    steps:
      - run:
          name: SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.organization=${SONAR_ORGANIZATION} \
              -Dsonar.sources=${SONAR_SOURCES_DIR} \
              -Dsonar.login=${SONAR_TOKEN}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - docker_build_and_push:
          requires:
            - build
      - sonar_analysis:
          requires:
            - build
