version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.8  # Adjust as needed

jobs:
  checkout:
    executor: default
    steps:
      - checkout
      - run:
          name: Load Scripts
          command: |
            mkdir -p $HOME/shared-libraries
            cp -r Jenkins/shared-libraries/* $HOME/shared-libraries/

  git_checkout:
    executor: default
    steps:
      - run:
          name: Checkout Source Code Repo
          command: |
            git clone -b $SOURCE_CODE_BRANCH_NAME $GIT_SOURCE_CODE_URL source-code || { echo 'Git clone failed'; exit 1; }
            ls -al  # List directory contents at this point
            cd source-code
            ls -al  # List contents of source-code directory
            git checkout $SOURCE_CODE_BRANCH_NAME || { echo 'Git checkout failed'; exit 1; }
            ls -al  # List contents to confirm directory structure

  build:
    executor: default
    steps:
      - run:
          name: Build with npm
          command: |
            cd source-code || { echo 'Directory source-code not found'; exit 1; }
            npm install
            npm run build

  unit_test:
    executor: default
    steps:
      - run:
          name: Unit Test
          command: |
            cd source-code || { echo 'Directory source-code not found'; exit 1; }
            npm test

  sonar_analysis:
    executor: default
    steps:
      - run:
          name: SonarQube Analysis
          command: |
            cd source-code || { echo 'Directory source-code not found'; exit 1; }
            # Add your SonarQube analysis command here

  docker_build:
    executor: default
    steps:
      - run:
          name: Docker Build
          command: |
            cd source-code || { echo 'Directory source-code not found'; exit 1; }
            docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .

  docker_scan:
    executor: default
    steps:
      - run:
          name: Docker Scan
          command: |
            # Add your Docker scan command here

  docker_publish:
    executor: default
    steps:
      - run:
          name: Docker Publish
          command: |
            echo "$DOCKER_CREDENTIAL" | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_REPO/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - git_checkout
      - build
      - unit_test
      - sonar_analysis
      - docker_build
      - docker_scan
      - docker_publish
