version: 2.1

executors:
  default:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  setup:
    executor: default
    steps:
      - checkout

      - run:
          name: Install Basic Utilities
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip wget curl bash software-properties-common gnupg

      - run:
          name: Install Groovy
          command: |
            wget -qO /tmp/groovy.zip https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/apache-groovy-binary-5.0.0-alpha-9.zip
            sudo unzip /tmp/groovy.zip -d /opt
            sudo ln -sf /opt/groovy-5.0.0-alpha-9/bin/groovy /usr/local/bin/groovy
            sudo chmod +x /opt/groovy-5.0.0-alpha-9/bin/groovy

      - run:
          name: List Java Installations
          command: |
            ls -l /usr/lib/jvm

      - run:
          name: Set JAVA_HOME and PATH
          command: |
            export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH
            echo "JAVA_HOME is set to: $JAVA_HOME"
            ls -l $JAVA_HOME/bin/java
            java -version

      - run:
          name: Set GROOVY_HOME and PATH
          command: |
            export GROOVY_HOME=/opt/groovy-5.0.0-alpha-9
            export PATH=$GROOVY_HOME/bin:$PATH
            echo "GROOVY_HOME is set to: $GROOVY_HOME"
            groovy --version

      - run:
          name: Run Build Script
          command: |
            groovy Jenkins/shared-libraries/src/org/common/build/BuildWithNpm.groovy

workflows:
  version: 2
  build:
    jobs:
      - setup
