version: 2.1

executors:
  java-node-docker-executor:
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      JAVA_HOME: /usr/local/openjdk-11
      GROOVY_HOME: /usr/local/groovy
      PATH: /usr/local/groovy/bin:/usr/local/openjdk-11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    working_directory: /home/circleci/project

jobs:
  install_dependencies:
    executor: java-node-docker-executor
    steps:
      - checkout
      - run:
          name: Install Node.js and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node --version
            npm --version
      - run:
          name: Install Groovy
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip
            wget https://dl.bintray.com/groovy/maven/apache-groovy-sdk-4.0.11.zip
            unzip apache-groovy-sdk-4.0.11.zip -d /usr/local
            sudo mv /usr/local/apache-groovy-sdk-4.0.11 /usr/local/groovy
            export PATH=$PATH:/usr/local/groovy/bin
            groovy --version
      - run:
          name: Install SonarQube Scanner
          command: |
            curl -fsSL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip -o sonar-scanner.zip
            unzip sonar-scanner.zip -d /usr/local
            sudo mv /usr/local/sonar-scanner-4.6.2.2472-linux /usr/local/sonar-scanner
            export PATH=$PATH:/usr/local/sonar-scanner/bin
            sonar-scanner --version
      - run:
          name: Check Docker Installation
          command: |
            if ! command -v docker &> /dev/null; then
              echo "Docker not found, installing Docker..."
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
            else
              echo "Docker is already installed."
            fi
            docker --version

  # Other jobs remain the same

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install_dependencies
      - load_scripts:
          requires:
            - install_dependencies
      - build:
          requires:
            - load_scripts
      - test:
          requires:
            - build
      - sonar_analysis:
          requires:
            - test
      - docker_build:
          requires:
            - sonar_analysis
      - docker_scan:
          requires:
            - docker_build
      - docker_publish:
          requires:
            - docker_scan
