version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14  # Replace with the Node.js version you need
    working_directory: ~/project

jobs:
  install_java_groovy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Java and Groovy
          command: |
            # Install Java
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk
            export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH
            
            # Verify Java installation
            java -version
            javac -version
            
            # Install Groovy
            wget https://archive.apache.org/dist/groovy/4.0.11/distribution/apache-groovy-sdk-4.0.11.zip
            unzip apache-groovy-sdk-4.0.11.zip
            sudo mv groovy-4.0.11 /usr/local/groovy
            export PATH=$PATH:/usr/local/groovy/bin
            
            # Verify Groovy installation
            groovy --version

  load_scripts:
    parameters:
      baseDir:
        type: string
        default: "Jenkins/shared-libraries"
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Load Scripts
          command: |
            baseDir="${CIRCLE_WORKING_DIRECTORY}/${BASE_DIR}"
            # Function to load Groovy
