version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16  # Update Node.js version as needed

jobs:
  setup:
    executor: node-executor
    parameters:
      # Your existing parameters here...

    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install Groovy
          command: |
            if ! command -v groovy &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y wget openjdk-11-jdk
              wget https://dl.bintray.com/groovy/maven/groovy-sdk-3.0.9.zip
              unzip groovy-sdk-3.0.9.zip
              sudo mv groovy-3.0.9 /opt/groovy
              sudo ln -s /opt/groovy/bin/groovy /usr/local/bin/groovy
            else
              echo "Groovy is already installed"
            fi

      - run:
          name: Debug Groovy Installation
          command: |
            # Check if groovy is in PATH
            echo "Checking if Groovy is in PATH:"
            which groovy

            # List installed Groovy files
            echo "Listing contents of /opt/groovy:"
            ls -l /opt/groovy

            # Verify symlink
            echo "Checking symlink for groovy:"
            ls -l /usr/local/bin/groovy

      # Your existing steps here...

  build:
    executor: node-executor
    parameters:
      # Your existing parameters here...

    steps:
      - checkout:
          path: ~/project

      - run:
          name: Print Parameters
          command: |
            # Print parameters for debugging purposes
            echo "GIT_SOURCE_CODE_URL: << parameters.GIT_SOURCE_CODE_URL >>"
            echo "SOURCE_CODE_BRANCH_NAME: << parameters.SOURCE_CODE_BRANCH_NAME >>"
            echo "DOCKER_REPO: << parameters.DOCKER_REPO >>"
            echo "DOCKER_IMAGE_NAME: << parameters.DOCKER_IMAGE_NAME >>"
            echo "DOCKER_IMAGE_TAG: << parameters.DOCKER_IMAGE_TAG >>"
            echo "SONAR_PROJECT_KEY: << parameters.SONAR_PROJECT_KEY >>"
            echo "SONAR_ORGANIZATION: << parameters.SONAR_ORGANIZATION >>"
            echo "SONAR_SOURCES_DIR: << parameters.SONAR_SOURCES_DIR >>"

      - run:
          name: Load and Execute Build Groovy Script
          command: |
            cd ~/project
            baseDir="${PWD}/Jenkins/shared-libraries"

            loadAndExecuteGroovyScript() {
              type=$1
              technology=$2
              scriptName=$3
              scriptPath="${baseDir}/${type}/${technology}/${scriptName}.groovy"
              if [ -f ${scriptPath} ]; then
                echo "Executing ${scriptPath}"
                groovy ${scriptPath}
              else
                echo "Script ${scriptPath} not found!"
                exit 1
              fi
            }

            loadAndExecuteGroovyScript "src/org/common" "build" "BuildWithNpm"

workflows:
  version: 2
  setup_and_build:
    jobs:
      - setup:
          GIT_SOURCE_CODE_URL: "https://github.com/bharathkoptit/build_js_react_app.git"
          SOURCE_CODE_BRANCH_NAME: "master"
          GIT_SOURCE_CODE_CREDENTIAL: "bharathkoptit/******"
          DOCKER_REPO: "bharathoptdocker"
          DOCKER_IMAGE_NAME: "optit-lab-service"
          DOCKER_IMAGE_TAG: "latest"
          DOCKER_CREDENTIAL: "bharathoptdocker/******"
          SONAR_PROJECT_KEY: "myreactorg_myreactorg"
          SONAR_ORGANIZATION: "myreactorg"
          SONAR_SOURCES_DIR: "."
          SONAR_TOKEN: "your-sonar-token"
      - build:
          requires:
            - setup
          GIT_SOURCE_CODE_URL: "https://github.com/bharathkoptit/build_js_react_app.git"
          SOURCE_CODE_BRANCH_NAME: "master"
          GIT_SOURCE_CODE_CREDENTIAL: "bharathkoptit/******"
          DOCKER_REPO: "bharathoptdocker"
          DOCKER_IMAGE_NAME: "optit-lab-service"
          DOCKER_IMAGE_TAG: "latest"
          DOCKER_CREDENTIAL: "bharathoptdocker/******"
          SONAR_PROJECT_KEY: "myreactorg_myreactorg"
          SONAR_ORGANIZATION: "myreactorg"
          SONAR_SOURCES_DIR: "."
          SONAR_TOKEN: "your-sonar-token"
