version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.8

jobs:
  git_checkout:
    executor: default
    steps:
      - checkout
      - run:
          name: Define Groovy Scripts Location
          command: |
            echo "export BASE_DIR=${CIRCLE_WORKING_DIRECTORY}/shared-libraries" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install Java and other packages
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip wget openjdk-11-jdk

      - run:
          name: Install Groovy
          command: |
            wget https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/apache-groovy-binary-5.0.0-alpha-9.zip -O groovy.zip
            mkdir -p $HOME/groovy
            unzip groovy.zip -d $HOME/groovy

      - run:
          name: Set GROOVY_HOME and PATH
          command: |
            echo 'export GROOVY_HOME=$HOME/groovy/groovy-5.0.0-alpha-9' >> $BASH_ENV
            echo 'export PATH=$GROOVY_HOME/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Verify Groovy Installation
          command: |
            if [ -f "$GROOVY_HOME/bin/groovy" ]; then
              echo "Groovy installed successfully."
              groovy --version
            else
              echo "Groovy installation failed or not found."
              exit 1
            fi

      - persist_to_workspace:
          root: $HOME
          paths:
            - groovy

  build:
    executor: default
    steps:
      - attach_workspace:
          at: $HOME
      - run:
          name: Set GROOVY_HOME and PATH
          command: |
            echo 'export GROOVY_HOME=$HOME/groovy/groovy-5.0.0-alpha-9' >> $BASH_ENV
            echo 'export PATH=$GROOVY_HOME/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Verify PATH
          command: |
            echo "PATH is: $PATH"
            which groovy || (echo "Groovy command not found!" && exit 1)

      - run:
          name: Run Groovy Script
          command: |
            groovy Jenkins/shared-libraries/src/org/common/build/BuildWithNpm.groovy | tee build-script.log
