version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/openjdk:17.0.11-browsers
    working_directory: ~/project

jobs:
  setup_environment:
    executor: docker-executor
    steps:
      - checkout
      
      # Install basic utilities
      - run:
          name: Install basic utilities
          command: |
            sudo apt-get update
            sudo apt-get install -y curl gnupg unzip

      # Install Groovy
      - run:
          name: Install Groovy
          command: |
            curl -s https://groovy.jfrog.io/artifactory/distributions/groovy-binary-3.0.9.zip -o groovy.zip
            sudo unzip groovy.zip -d /opt
            sudo ln -s /opt/groovy-3.0.9/bin/groovy /usr/local/bin/groovy
            sudo ln -s /opt/groovy-3.0.9/bin/groovysh /usr/local/bin/groovysh
            sudo ln -s /opt/groovy-3.0.9/bin/groovyc /usr/local/bin/groovyc
            sudo ln -s /opt/groovy-3.0.9/bin/groovyConsole /usr/local/bin/groovyConsole

      # Install Trivy
      - run:
          name: Install Trivy
          command: |
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      # Install SonarQube Scanner
      - run:
          name: Install SonarQube Scanner
          command: |
            curl -Lo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
            unzip sonar-scanner.zip -d /opt
            sudo ln -s /opt/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner /usr/local/bin/sonar-scanner

      # Verify installations
      - run:
          name: Verify installations
          command: |
            java -version
            groovy -version
            trivy --version
            sonar-scanner --version

  build_and_deploy:
    executor: docker-executor
    steps:
      - checkout
      
      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t my-custom-image:latest .

      # Run Docker container and execute commands
      - run:
          name: Run Docker container
          command: |
            docker run --rm my-custom-image:latest bash -c "java -version && groovy -version && trivy --version && sonar-scanner --version"

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup_environment
      - build_and_deploy:
          requires:
            - setup_environment
