version: 2.1

executors:
  default:
    docker:
      - image: bharathoptdocker/nodjs-java17-trivy:latest  # Custom Docker image

jobs:
  setup:
    executor: default
    steps:
      - checkout
      
      # Set up remote Docker
      - setup_remote_docker:
          version: docker23  # Choose a supported Docker version 

      # Check Docker version 
      - run:
          name: Check Docker Version
          command: |
            docker --version

      # Build Docker Image
      - run:
          name: Build Docker Image
          command: |
            if [ -z "$DOCKER_REPO" ] || [ -z "$DOCKER_IMAGE_NAME" ] || [ -z "$DOCKER_IMAGE_TAG" ]; then
              echo "Docker environment variables are not set."
              exit 1
            fi
            docker build -t ${DOCKER_REPO}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} .

      # Scan Docker Image with Trivy
      - run:
          name: Scan Docker Image
          command: |
            trivy image ${DOCKER_REPO}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}

      # Publish Docker Image
      - run:
          name: Publish Docker Image
          command: |
            if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ]; then
              echo "Docker credentials are not set."
              exit 1
            fi
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push ${DOCKER_REPO}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}

workflows:
  version: 2
  build:
    jobs:
      - setup
