version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.8

jobs:
  # Checkout and prepare the workspace
  prepare:
    executor: default
    steps:
      - checkout
      - run:
          name: Define Groovy Scripts Location
          command: |
            echo "export BASE_DIR=${CIRCLE_WORKING_DIRECTORY}/build_js_react_app/Jenkins/shared-libraries" >> $BASH_ENV
            echo "BASE_DIR is set to: ${BASE_DIR}"
            source $BASH_ENV
      - persist_to_workspace:
          root: .
          paths:
            - .

  # Build with NPM
  build:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build with NPM
          command: |
            mkdir -p reports
            groovy ${BASE_DIR}/src/org/common/build/BuildWithNpm.groovy > reports/build.log 2>&1
            cat reports/build.log
      - persist_to_workspace:
          root: .
          paths:
            - .

  # Run Unit Tests
  unit_test:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Unit Tests
          command: |
            mkdir -p reports
            groovy ${BASE_DIR}/vars/common/test/RunUnitTests.groovy > reports/unit-test.log 2>&1
            cat reports/unit-test.log
      - persist_to_workspace:
          root: .
          paths:
            - .

  # SonarQube Analysis
  sonar_analysis:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: SonarQube Analysis
          command: |
            mkdir -p reports
            groovy ${BASE_DIR}/vars/common/codeAnalysis/PerformSonarAnalysisForReactjs.groovy \
              --sonarProjectKey ${SONAR_PROJECT_KEY} \
              --sonarOrganization ${SONAR_ORGANIZATION} \
              --sonarSourcesDir ${SONAR_SOURCES_DIR} \
              --sonarToken ${SONAR_TOKEN} > reports/sonar-analysis.log 2>&1
            cat reports/sonar-analysis.log
      - persist_to_workspace:
          root: .
          paths:
            - .

  # Docker Build
  docker_build:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Docker Build
          command: |
            mkdir -p reports
            groovy ${BASE_DIR}/vars/common/dockerUtil/DockerBuild.groovy \
              --dockerImageName ${DOCKER_IMAGE_NAME} \
              --dockerImageTag ${DOCKER_IMAGE_TAG} > reports/docker-build.log 2>&1
            cat reports/docker-build.log
      - persist_to_workspace:
          root: .
          paths:
            - .

  # Docker Scan
  docker_scan:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Docker Scan
          command: |
            mkdir -p reports
            groovy ${BASE_DIR}/vars/common/dockerUtil/DockerScan.groovy \
              --dockerImageName ${DOCKER_IMAGE_NAME} > reports/docker-scan.log 2>&1
            cat reports/docker-scan.log
      - persist_to_workspace:
          root: .
          paths:
            - .

  # Docker Publish
  docker_publish:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Docker Publish
          command: |
            mkdir -p reports
            groovy ${BASE_DIR}/vars/common/containerPublish/DockerHubPublish.groovy \
              --dockerImageName ${DOCKER_IMAGE_NAME} \
              --dockerRepo ${DOCKER_REPO} \
              --dockerImageTag ${DOCKER_IMAGE_TAG} \
              --dockerCredential ${DOCKER_CREDENTIAL} > reports/docker-publish.log 2>&1
            cat reports/docker-publish.log

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
      - unit_test:
          requires:
            - build
      - sonar_analysis:
          requires:
            - unit_test
      - docker_build:
          requires:
            - sonar_analysis
      - docker_scan:
          requires:
            - docker_build
      - docker_publish:
          requires:
            - docker_scan
