version: 2.1

executors:
  java-node-docker-executor:
    docker:
      - image: circleci/python:3.8  # Choose an appropriate base image

jobs:
  install_dependencies:
    executor: java-node-docker-executor
    steps:
      - checkout
      - run:
          name: Install Node.js and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node --version
            npm --version
      - run:
          name: Install Groovy
          command: |
            wget https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/apache-groovy-binary-2.4.10.zip
            unzip apache-groovy-binary-2.4.10.zip
            sudo mv groovy-2.4.10 /usr/local/groovy
            export PATH=$PATH:/usr/local/groovy/bin
            groovy --version
      - run:
          name: Install SonarQube Scanner
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli-4.6.2.2472-linux.zip
            sudo mv sonar-scanner-4.6.2.2472-linux /usr/local/sonar-scanner
            export PATH=$PATH:/usr/local/sonar-scanner/bin
            sonar-scanner --version
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo usermod -aG docker $(whoami)
            docker --version

  build:
    executor: java-node-docker-executor
    steps:
      - checkout
      - run:
          name: Build Project
          command: |
            # Add your build commands here

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
