version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.8

jobs:
  setup:
    executor: default
    steps:
      - checkout

      # Install required packages
      - run:
          name: Install required packages
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip wget

      # Download and extract Groovy
      - run:
          name: Download Groovy
          command: |
            wget https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/apache-groovy-binary-5.0.0-alpha-9.zip -O groovy.zip

      - run:
          name: Extract Groovy
          command: |
            sudo unzip groovy.zip -d /opt

      # Verify extracted files
      - run:
          name: List contents of /opt
          command: |
            ls -l /opt

      # Verify the installation
      - run:
          name: Verify Groovy Installation
          command: |
            # Find the actual path to the Groovy binary
            groovy_bin=$(find /opt -name groovy -type f -executable)
            echo "Groovy binary found at: $groovy_bin"
            sudo $groovy_bin -version

      # Clean up
      - run:
          name: Clean up
          command: |
            rm -f groovy.zip

workflows:
  version: 2
  build:
    jobs:
      - setup
