version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      # Print working directory
      - run:
          name: Print Working Directory
          command: |
            echo "Current working directory:"
            pwd

      # Set BASE_DIR environment variable
      - run:
          name: Set BASE_DIR
          command: |
            echo "export BASE_DIR=${CIRCLE_WORKING_DIRECTORY}/build_js_react_app/Jenkins/shared-libraries" >> $BASH_ENV
            source $BASH_ENV
            echo "BASE_DIR is set to: ${BASE_DIR}"

      # Verify and print directory structure
      - run:
          name: List Directory Structure
          command: |
            echo "Directory structure at BASE_DIR:"
            ls -R ${BASE_DIR} || echo "Directory not found"

      # Run Groovy script if the path is valid
      - run:
          name: Run Groovy Script
          command: |
            if [ -f "${BASE_DIR}/src/org/common/build/BuildWithNpm.groovy" ]; then
                groovy ${BASE_DIR}/src/org/common/build/BuildWithNpm.groovy > reports/build.log 2>&1
                cat reports/build.log
            else
                echo "Error: Groovy script not found at: ${BASE_DIR}/src/org/common/build/BuildWithNpm.groovy"
                exit 1
            fi
