version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/project

jobs:
  setup_environment:
    executor: docker-executor
    steps:
      - checkout
      
      # Install basic utilities
      - run:
          name: Install basic utilities
          command: |
            sudo apt-get update
            sudo apt-get install -y curl gnupg

   

      # Install Java and Groovy
      - run:
          name: Install Java and Groovy
          command: |
            sudo apt-get install -y openjdk-11-jdk
            curl -s https://groovy.jfrog.io/artifactory/distributions/groovy-binary-3.0.9.zip -o groovy.zip
            unzip groovy.zip -d /opt
            sudo ln -s /opt/groovy-3.0.9/bin/groovy /usr/local/bin/groovy
            sudo ln -s /opt/groovy-3.0.9/bin/groovysh /usr/local/bin/groovysh
            sudo ln -s /opt/groovy-3.0.9/bin/groovyc /usr/local/bin/groovyc
            sudo ln -s /opt/groovy-3.0.9/bin/groovyConsole /usr/local/bin/groovyConsole

      # Verify installations
      - run:
          name: Verify installations
          command: |
            java -version
            groovy -version
            trivy --version
            sonar-scanner --version

  build_and_deploy:
    executor: docker-executor
    steps:
      - checkout
      
      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t my-custom-image:latest .

      # Run Docker container and execute commands
      - run:
          name: Run Docker container
          command: |
            docker run --rm my-custom-image:latest bash -c "java -version && groovy -version && trivy --version && sonar-scanner --version"

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup_environment
      - build_and_deploy:
          requires:
            - setup_environment
