version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14  # Replace with the Node.js version you need
    working_directory: ~/project

jobs:
  install_groovy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Groovy
          command: |
            wget https://archive.apache.org/dist/groovy/4.0.11/distribution/apache-groovy-sdk-4.0.11.zip
            unzip apache-groovy-sdk-4.0.11.zip
            sudo mv groovy-4.0.11 /usr/local/groovy
            export PATH=$PATH:/usr/local/groovy/bin
            groovy --version

  load_scripts:
    parameters:
      baseDir:
        type: string
        default: "Jenkins/shared-libraries"
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Load Scripts
          command: |
            baseDir="${CIRCLE_WORKING_DIRECTORY}/${BASE_DIR}"
            # Function to load Groovy scripts
            loadScript() {
              type=$1
              technology=$2
              scriptName=$3
              scriptPath="${baseDir}/${type}/${technology}/${scriptName}.groovy"
              groovy "${scriptPath}"
            }

            # Load Groovy scripts
            gitCheckoutScript=$(loadScript "vars/common/scm-util" "git" "GitCheckout")
            sonarScript=$(loadScript "vars/common" "codeAnalysis" "PerformSonarAnalysisForReactjs")
            dockerBuildScript=$(loadScript "vars/common" "dockerUtil" "DockerUtil")
            dockerPublishScript=$(loadScript "vars/common" "containerPublish" "DockerHubPublish")
            dockerScanScript=$(loadScript "vars/common" "dockerUtil" "DockerScan")
            buildWithNpmScript=$(loadScript "src/org/common" "build" "BuildWithNpm")
            unitTestWithNpmScript=$(loadScript "src/org/common" "unitTest" "UnitTestWithNpm")

  git_checkout:
   
