version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.8

jobs:
  git_checkout:
    executor: default
    steps:
      - checkout
      - run:
          name: Define Groovy Scripts Location
          command: |
            echo "export BASE_DIR=${CIRCLE_WORKING_DIRECTORY}/shared-libraries" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install Java and other packages
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip wget openjdk-11-jdk

      # Install Groovy
      - run:
          name: Install Groovy
          command: |
            wget https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/apache-groovy-binary-5.0.0-alpha-9.zip -O groovy.zip
            mkdir -p $HOME/groovy
            unzip groovy.zip -d $HOME/groovy

      # Set GROOVY_HOME and update PATH environment variable
      - run:
          name: Set GROOVY_HOME and PATH
          command: |
            echo 'export GROOVY_HOME=$HOME/groovy/groovy-5.0.0-alpha-9' >> $BASH_ENV
            echo 'export PATH=$GROOVY_HOME/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

      # Verify Groovy installation
      - run:
          name: Verify Groovy Installation
          command: |
            groovy --version || $HOME/groovy/groovy-5.0.0-alpha-9/bin/groovy --version

      # Save environment variables to workspace
      - persist_to_workspace:
          root: $HOME/groovy
          paths:
            - groovy-5.0.0-alpha-9

  build:
    executor: default
    steps:
      - attach_workspace:
          at: $HOME/groovy
      - run:
          name: Set GROOVY_HOME and PATH
          command: |
            echo 'export GROOVY_HOME=$HOME/groovy/groovy-5.0.0-alpha-9' >> $BASH_ENV
            echo 'export PATH=$GROOVY_HOME/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Build with NPM
          command: |
            groovy Jenkins/shared-libraries/src/org/common/build/BuildWithNpm.groovy | tee build-script.log

  # Continue with the other jobs similarly
