version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:16

jobs:
  print_parameters:
    executor: docker-executor
    parameters:
      git_source_code_url:
        type: string
        default: 'https://github.com/example/repo'
      source_code_branch_name:
        type: string
        default: 'main'
      docker_repo:
        type: string
        default: 'my-docker-repo'
      docker_image_name:
        type: string
        default: 'myapp'
      docker_image_tag:
        type: string
        default: 'latest'
      sonar_project_key:
        type: string
        default: 'sonar-project'
      sonar_organization:
        type: string
        default: 'sonar-org'
      sonar_sources_dir:
        type: string
        default: 'src'
      sonar_token:
        type: string
        default: 'sonar-token'

    steps:
      - run:
          name: Print Parameters
          command: |
            echo "Git Source Code URL: << parameters.git_source_code_url >>"
            echo "Source Code Branch Name: << parameters.source_code_branch_name >>"
            echo "Docker Repo: << parameters.docker_repo >>"
            echo "Docker Image Name: << parameters.docker_image_name >>"
            echo "Docker Image Tag: << parameters.docker_image_tag >>"
            echo "Sonar Project Key: << parameters.sonar_project_key >>"
            echo "Sonar Organization: << parameters.sonar_organization >>"
            echo "Sonar Sources Directory: << parameters.sonar_sources_dir >>"
            echo "Sonar Token: << parameters.sonar_token >>"

workflows:
  version: 2
  print_parameters_workflow:
    jobs:
      - print_parameters
