version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.8

jobs:
  git_checkout:
    executor: default
    steps:
      - checkout

      - run:
          name: Install Java and other packages
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip wget openjdk-11-jdk

      - run:
          name: Install Groovy
          command: |
            wget -qO /tmp/groovy.zip https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/apache-groovy-binary-5.0.0-alpha-9.zip
            sudo unzip /tmp/groovy.zip -d /opt
            sudo ln -sf /opt/groovy-5.0.0-alpha-9/bin/groovy /usr/local/bin/groovy
            sudo chmod +x /opt/groovy-5.0.0-alpha-9/bin/groovy

      - run:
          name: Set GROOVY_HOME and PATH
          command: |
            echo 'export GROOVY_HOME=/opt/groovy-5.0.0-alpha-9' >> $BASH_ENV
            echo 'export PATH=$GROOVY_HOME/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Verify Groovy Installation
          command: |
            groovy --version || /opt/groovy-5.0.0-alpha-9/bin/groovy --version

      - run:
          name: Install Node.js and npm
          command: |
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node --version
            npm --version

      - run:
          name: Run Build Script
          command: |
            groovy Jenkins/shared-libraries/src/org/common/build/BuildWithNpm.groovy

      - run:
          name: Run Test Script
          command: |
            groovy Jenkins/shared-libraries/src/org/common/unitTest/UnitTestWithNpm.groovy

      - run:
          name: Install SonarScanner
          command: |
            # Download SonarScanner
            wget -qO /tmp/sonar-scanner.zip https://sonarcloud.io/static/cpp/sonar-scanner-cli-4.6.2.2472-linux.zip

            # Verify the download
            ls -lh /tmp/sonar-scanner.zip
            file /tmp/sonar-scanner.zip

            # Inspect the ZIP file contents
            unzip -l /tmp/sonar-scanner.zip

            # Create directory for SonarScanner
            sudo mkdir -p /opt/sonar-scanner

            # Unzip the file
            sudo unzip -v /tmp/sonar-scanner.zip -d /opt/sonar-scanner || {
              echo "Unzip failed. Check if /tmp/sonar-scanner.zip is a valid ZIP file."
              exit 1
            }

            # Create symbolic link and set permissions
            sudo ln -sf /opt/sonar-scanner/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner /usr/local/bin/sonar-scanner
            sudo chmod +x /usr/local/bin/sonar-scanner

            # Verify installation
            sonar-scanner --version

      - run:
          name: Run SonarScanner
          command: |
            sonar-scanner \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.organization=${SONAR_ORGANIZATION} \
              -Dsonar.sources=${SONAR_SOURCES_DIR} \
              -Dsonar.java.binaries=${SONAR_BINARIES_DIR} \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${SONAR_TOKEN} \
              > sonar-scanner.log 2>&1 || {
                echo "SonarScanner failed with exit code $?. See sonar-scanner.log for details."
                cat sonar-scanner.log
                exit 1
              }

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build Docker Image
          command: |
            groovy Jenkins/shared-libraries/vars/common/dockerUtil/DockerUtil.groovy

      - run:
          name: Scan Docker Image
          command: |
            groovy Jenkins/shared-libraries/vars/common/dockerUtil/DockerScan.groovy

      - run:
          name: Publish Docker Image
          command: |
            groovy Jenkins/shared-libraries/vars/common/containerPublish/DockerHubPublish.groovy

workflows:
  version: 2
  build:
    jobs:
      - git_checkout
